js: add MakeFullWrapper to expose exported methods and struct fields.
gopherjs/gopherjs pull request #1112
Opened 2022-04-04 03:50 UTC by JounQin

rebase for #790

---

Currently the documentation for js.MakeWrapper is:

> "MakeWrapper creates a JavaScript object which has wrappers for the
exported methods of i. Use explicit getter and setter methods to expose
struct fields to JavaScript."

Where the value a struct value (or more
interestingly a pointer to a struct value) we can actually auto-generate
getters and setters for exported fields in the JavaScript world, rather
than requiring explicit getters and setters to be defined on the Go
side.

We do this via a new MakeFullWrapper method.

2022-04-04 20:10 UTC, nevkontakte commented
Thanks for doing the rebase! Upon the first pass the change looks good, but it is a part of the codebase I'm not very familiar with. I'll need a day or two more to understand this change in more detail.

Please disregard the failed check, it appears to be a bug in the check itself, unrelated to this PR.

2022-04-10 13:37 UTC, nevkontakte requested changes
@JounQin sorry for the delay, I had a very busy week at work. I left a few minor comments to improve code readability. I also pushed a fix for the failed GitHub Action, if you rebase on the latest master, the check should pass.

2022-04-10 13:37 UTC, nevkontakte commented on js/js.go
> +	v := InternalObject(i)
readability: let's use a more descriptive name, for example `internalObj`.

2022-04-10 13:37 UTC, nevkontakte commented on js/js.go
> +	o := Global.Get("Object").New()
readability: let's use a more descriptive name here too, for example `wrapperObj`.

2022-04-10 13:37 UTC, nevkontakte commented on js/js.go
> +	})
This function can be simplified greatly using the fact that GopherJS converts Go maps into JavaScript objects. Something like this:

```go
defineProperty := func(k string, descriptor M) {
  Global.Get("Object").Call("defineProperty", o, k, descriptor)
}

defineProperty("__internal_object__", M{
  "value": v,
})
```

(Note that `M` is a type defined in the `js` package: https://pkg.go.dev/github.com/gopherjs/gopherjs/js#M).

2022-04-10 13:37 UTC, nevkontakte commented on js/js.go
> +		// so we do some string operations by hand
readability: Comments should be full sentences starting with a capital letter and ending with punctuation. Same below.

2022-04-17 15:31 UTC, nevkontakte commented on js/js.go
> +// for the non-embedded exported fields of i. Values accessed via these methods
I think it's more of a technical limitation, although not impossible to overcome. You'd have to do a lot more introspection of the exported object, which is difficult to do without reflect.

2022-04-17 15:35 UTC, nevkontakte commented
@JounQin I'd like to merge this pull request and make a GopherJS release with it. If you need help with addressing the comments I left, you could enable "Allow edits and access to secrets by maintainers" on this PR, and I could give it a go.

2022-04-17 15:51 UTC, JounQin commented
@nevkontakte 

<img width="256" alt="image" src="https://user-images.githubusercontent.com/8336744/163722128-04c50707-cc3a-4155-855a-1ea11e6e6bc6.png">

I've already enabled this feature when PR open, feel free to change.

2022-04-17 15:56 UTC, nevkontakte commented
Strange, I get an error when I try to push commits to it:

```
$ git push JounQuin getters -f
ERROR: Permission to JounQin/gopherjs.git denied to nevkontakte.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I'll try to figure out what I'm going wrong :)

2022-04-17 16:30 UTC, nevkontakte commented
@JounQin  I figured out the issue. Your repository is a fork of https://github.com/myitcv/gopherjs, not this repository. Apparently, in GitHub's eyes this [disqualifies](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork) me from being able to edit this pull request contents:

> You can only make commits on pull request branches that:
>  - are opened in a repository that you have push access to and that were __created from a fork of that repository__.

Do you need my assistance to address the review comments? I could take your branch and make yet another PR from it if so.

2022-04-18 01:53 UTC, JounQin commented
@nevkontakte Please help to review again.

2022-04-18 11:54 UTC, nevkontakte approved these changes

2022-04-18 11:54 UTC, nevkontakte commented
@JounQin thanks for addressing the comments, and thanks for the contribution!

2022-04-18 11:55 UTC, merged